# Generated by Django 4.0.1 on 2022-10-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='diabetic',
            field=models.BooleanField(default=0),
        ),
    ]
