# Generated by Django 4.0.5 on 2022-10-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0002_alter_profile_diabetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugar',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
