# Generated by Django 4.1.2 on 2022-11-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='createdAt',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='updatedAt',
            new_name='updated',
        ),
    ]
