# Generated by Django 4.0.5 on 2022-10-04 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_patient_note_commenet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commenet',
            new_name='Comment',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replyTo', to='healthApp.comment')),
                ('replyFromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userFromReply', to='healthApp.user')),
                ('replyToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userToReply', to='healthApp.user')),
            ],
        ),
    ]
