# Generated by Django 4.0.5 on 2022-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_rename_commenet_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='dose',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='freq',
        ),
        migrations.AddField(
            model_name='taken',
            name='dose',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taken',
            name='freq',
            field=models.CharField(default='daily', max_length=255),
        ),
    ]
