# Generated by Django 4.0.5 on 2022-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0006_remove_medication_dose_remove_medication_freq_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taken',
            name='freq',
        ),
        migrations.AddField(
            model_name='week',
            name='freq',
            field=models.CharField(default='daily', max_length=255),
        ),
    ]
